import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Teaching Sidebars
 * 
 * We use a defined structure for the 4 core modules of the "Physical AI" curriculum.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System',
      items: [{ type: 'autogenerated', dirName: 'module-1-ros2' }],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin',
      items: [{ type: 'autogenerated', dirName: 'module-2-digital-twin' }],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 3: The Brain',
      items: [{ type: 'autogenerated', dirName: 'module-3-nvidia-isaac' }],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Module 4: The Body',
      items: [{ type: 'autogenerated', dirName: 'module-4-vla' }],
      collapsed: false,
    },
  ],
};

export default sidebars;
