@echo off
cd /d "%~dp0"
echo Starting Backend Server...
echo Activating Virtual Environment...
call backend\venv\Scripts\activate.bat
echo Installing Requirements...
pip install -r backend/requirements.txt
echo Running Uvicorn...
uvicorn backend.main:app --reload
pause
